### ISSUE TITLE
Lit Redstone Ore Block Crash 1.8

### ISSUE THREAD

**Issue by ChronomegaIV** [Chicken-Bones/NotEnoughItems#148]
Tried using both 1281 and 1282 builds of Forge. Made sure everything was completely up to date. Running Liteloader 1.8 with Forge 1282 for 1.8, ChickenCore and NEI along with Voxelmap. When using Highlighting mode, lit redstone ore blocks crash the client. Server remains active with no issues. Below is the error dump. Any other info you need, let me know.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 1/9/15 10:58 AM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=minecraft:lit_redstone_ore, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at codechicken.nei.DefaultHighlightHandler.handleTextData(DefaultHighlightHandler.java:32)
	at codechicken.nei.api.ItemInfo.getText(ItemInfo.java:498)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:52)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at codechicken.nei.DefaultHighlightHandler.handleTextData(DefaultHighlightHandler.java:32)
	at codechicken.nei.api.ItemInfo.getText(ItemInfo.java:498)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:52)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ChronomegaIV'/742, l='MpServer', x=700.59, y=54.00, z=70.95]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -241.00,100.00,-19.00 - World: (-241,100,-19), Chunk: (at 15,6,13 in -16,-2; contains blocks -256,0,-32 to -241,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 75036650 game time, 76378022 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 161 total; [EntityCow['Cow'/821, l='MpServer', x=712.34, y=86.00, z=35.44], EntityPig['Pig'/820, l='MpServer', x=712.38, y=86.00, z=45.53], EntityPlayerSP['ChronomegaIV'/742, l='MpServer', x=700.59, y=54.00, z=70.95], EntityItem['item.item.egg'/823, l='MpServer', x=708.50, y=86.00, z=47.13], EntityCow['Cow'/822, l='MpServer', x=711.22, y=86.00, z=35.44], EntityChicken['Chicken'/817, l='MpServer', x=706.94, y=86.00, z=47.19], EntityChicken['Chicken'/816, l='MpServer', x=707.56, y=86.02, z=51.03], EntityCow['Cow'/819, l='MpServer', x=710.00, y=86.00, z=39.53], EntityCow['Cow'/818, l='MpServer', x=713.53, y=86.00, z=36.69], EntityPig['Pig'/829, l='MpServer', x=711.25, y=86.00, z=41.94], EntityCow['Cow'/828, l='MpServer', x=710.03, y=86.00, z=36.63], EntityPig['Pig'/831, l='MpServer', x=707.19, y=86.00, z=43.81], EntityChicken['Chicken'/830, l='MpServer', x=713.31, y=86.00, z=47.44], EntityCow['Cow'/825, l='MpServer', x=708.75, y=86.02, z=35.44], EntityPig['Pig'/824, l='MpServer', x=708.91, y=86.00, z=42.56], EntityPig['Pig'/827, l='MpServer', x=713.50, y=86.00, z=42.78], EntityPig['Pig'/826, l='MpServer', x=710.09, y=86.02, z=41.44], EntitySheep['Sheep'/804, l='MpServer', x=707.19, y=86.00, z=55.88], EntityItem['item.item.egg'/805, l='MpServer', x=713.22, y=86.00, z=48.81], EntitySheep['Sheep'/806, l='MpServer', x=708.50, y=86.00, z=54.59], EntityChicken['Chicken'/807, l='MpServer', x=709.34, y=86.00, z=51.78], EntityChicken['Chicken'/800, l='MpServer', x=710.34, y=86.00, z=47.53], EntityRabbit['Rabbit'/801, l='MpServer', x=709.69, y=86.00, z=60.47], EntityRabbit['Rabbit'/802, l='MpServer', x=709.00, y=86.00, z=63.69], EntityRabbit['Rabbit'/803, l='MpServer', x=707.88, y=86.00, z=62.72], EntityRabbit['Rabbit'/813, l='MpServer', x=675.28, y=63.00, z=109.69], EntityRabbit['Rabbit'/814, l='MpServer', x=662.38, y=63.00, z=95.75], EntityCow['Cow'/815, l='MpServer', x=707.19, y=86.00, z=39.53], EntitySheep['Sheep'/808, l='MpServer', x=713.53, y=86.02, z=55.19], EntityRabbit['Rabbit'/809, l='MpServer', x=707.03, y=86.00, z=62.81], EntityItem['item.item.egg'/810, l='MpServer', x=713.88, y=86.00, z=51.88], EntitySheep['Sheep'/811, l='MpServer', x=707.19, y=86.00, z=57.53], EntityRabbit['Rabbit'/791, l='MpServer', x=711.66, y=86.00, z=59.28], EntityChicken['Chicken'/790, l='MpServer', x=706.94, y=86.00, z=50.41], EntityItem['item.item.egg'/788, l='MpServer', x=712.09, y=86.00, z=51.63], EntityRabbit['Rabbit'/787, l='MpServer', x=707.25, y=86.00, z=61.84], EntityRabbit['Rabbit'/786, l='MpServer', x=708.16, y=86.02, z=61.59], EntitySheep['Sheep'/785, l='MpServer', x=707.19, y=86.00, z=54.75], EntityRabbit['Rabbit'/784, l='MpServer', x=710.31, y=86.00, z=59.28], EntityRabbit['Rabbit'/799, l='MpServer', x=708.72, y=86.00, z=60.38], EntityChicken['Chicken'/798, l='MpServer', x=712.31, y=86.00, z=51.44], EntityRabbit['Rabbit'/797, l='MpServer', x=712.41, y=86.00, z=60.28], EntitySheep['Sheep'/796, l='MpServer', x=712.41, y=86.00, z=54.03], EntityCreeper['Creeper'/1122, l='MpServer', x=621.66, y=42.00, z=23.78], EntitySheep['Sheep'/795, l='MpServer', x=713.53, y=86.00, z=57.53], EntityRabbit['Rabbit'/794, l='MpServer', x=713.69, y=86.00, z=60.13], EntityRabbit['Rabbit'/793, l='MpServer', x=713.34, y=86.00, z=61.09], EntitySheep['Sheep'/792, l='MpServer', x=707.19, y=86.00, z=53.44], EntityRabbit['Rabbit'/774, l='MpServer', x=710.22, y=86.00, z=63.59], EntityChicken['Chicken'/775, l='MpServer', x=707.66, y=86.00, z=47.94], EntityRabbit['Rabbit'/772, l='MpServer', x=707.88, y=86.00, z=63.69], EntitySheep['Sheep'/773, l='MpServer', x=713.53, y=86.00, z=53.44], EntityItem['item.item.egg'/770, l='MpServer', x=707.53, y=86.00, z=50.97], EntityChicken['Chicken'/771, l='MpServer', x=713.06, y=86.00, z=51.44], EntityChicken['Chicken'/768, l='MpServer', x=708.06, y=86.02, z=51.78], EntityChicken['Chicken'/769, l='MpServer', x=713.78, y=86.00, z=51.47], EntityZombie['Zombie'/1617, l='MpServer', x=766.03, y=58.00, z=91.34], EntityRabbit['Rabbit'/782, l='MpServer', x=712.88, y=86.02, z=59.28], EntitySkeleton['Skeleton'/1616, l='MpServer', x=763.50, y=58.00, z=90.50], EntitySheep['Sheep'/783, l='MpServer', x=713.53, y=86.02, z=56.44], EntityRabbit['Rabbit'/780, l='MpServer', x=711.50, y=86.00, z=60.25], EntityZombie['Zombie'/1618, l='MpServer', x=765.44, y=58.00, z=92.16], EntityRabbit['Rabbit'/781, l='MpServer', x=713.69, y=86.02, z=59.28], EntitySheep['Sheep'/778, l='MpServer', x=711.13, y=86.00, z=57.53], EntitySheep['Sheep'/779, l='MpServer', x=708.41, y=86.00, z=57.53], EntityChicken['Chicken'/776, l='MpServer', x=710.84, y=86.00, z=48.63], EntityRabbit['Rabbit'/777, l='MpServer', x=707.72, y=86.00, z=59.75], EntitySpider['Spider'/883, l='MpServer', x=623.91, y=25.00, z=110.81], EntityZombie['Zombie'/884, l='MpServer', x=621.97, y=25.00, z=110.41], EntitySkeleton['Skeleton'/1576, l='MpServer', x=638.50, y=15.00, z=22.50], EntityBat['Bat'/887, l='MpServer', x=625.47, y=15.10, z=5.22], EntityRabbit['Rabbit'/886, l='MpServer', x=630.44, y=64.00, z=143.50], EntityCreeper['Creeper'/1574, l='MpServer', x=636.50, y=15.00, z=28.50], EntitySpider['Spider'/889, l='MpServer', x=621.69, y=25.00, z=114.50], EntitySkeleton['Skeleton'/1575, l='MpServer', x=632.88, y=17.00, z=32.50], EntityZombie['Zombie'/888, l='MpServer', x=640.50, y=27.00, z=147.50], EntityCreeper['Creeper'/1573, l='MpServer', x=635.50, y=15.00, z=28.50], EntityCreeper['Creeper'/1570, l='MpServer', x=656.28, y=15.00, z=17.22], EntityBat['Bat'/892, l='MpServer', x=627.42, y=46.18, z=14.66], EntityCreeper['Creeper'/1571, l='MpServer', x=655.94, y=16.00, z=16.38], o['unknown'/73, l='MpServer', x=700.59, y=62.00, z=70.95], EntityCreeper['Creeper'/1568, l='MpServer', x=658.50, y=15.00, z=13.50], EntityCreeper['Creeper'/1569, l='MpServer', x=656.66, y=15.00, z=18.03], EntityEnderman['Enderman'/864, l='MpServer', x=630.72, y=27.00, z=88.78], EntityZombie['Zombie'/866, l='MpServer', x=637.50, y=39.00, z=98.50], EntityZombie['Zombie'/869, l='MpServer', x=634.50, y=35.00, z=103.50], EntityBat['Bat'/1593, l='MpServer', x=630.45, y=27.91, z=142.14], EntityBat['Bat'/1592, l='MpServer', x=636.91, y=24.19, z=148.48], EntityCreeper['Creeper'/871, l='MpServer', x=659.97, y=39.00, z=4.53], EntityRabbit['Rabbit'/873, l='MpServer', x=629.53, y=63.00, z=114.06], EntityCreeper['Creeper'/874, l='MpServer', x=647.50, y=49.00, z=8.50], EntityRabbit['Rabbit'/877, l='MpServer', x=691.22, y=73.00, z=147.59], EntityRabbit['Rabbit'/878, l='MpServer', x=693.38, y=80.00, z=147.19], EntityHorse['Nightmare'/851, l='MpServer', x=724.53, y=86.00, z=61.75], EntityCow['Cow'/850, l='MpServer', x=713.50, y=86.00, z=38.34], EntityCow['Cow'/849, l='MpServer', x=708.47, y=86.02, z=36.78], EntityItem['item.item.egg'/848, l='MpServer', x=707.22, y=86.00, z=47.50], EntityHorse['Horse'/855, l='MpServer', x=728.41, y=87.00, z=56.72], EntityHorse['Horse'/854, l='MpServer', x=725.03, y=86.00, z=57.59], EntityHorse['Horse'/853, l='MpServer', x=725.69, y=86.00, z=55.88], EntityRabbit['Rabbit'/852, l='MpServer', x=723.28, y=86.00, z=60.13], EntityRabbit['Rabbit'/858, l='MpServer', x=644.44, y=67.00, z=91.78], EntityHorse['Horse'/856, l='MpServer', x=724.69, y=86.00, z=59.38], EntitySkeleton['Skeleton'/863, l='MpServer', x=681.72, y=75.00, z=142.28], EntityZombie['Zombie'/862, l='MpServer', x=661.53, y=16.00, z=16.09], EntityPig['Pig'/834, l='MpServer', x=707.19, y=86.00, z=45.06], EntityCow['Cow'/835, l='MpServer', x=707.63, y=86.00, z=38.13], EntityChicken['Chicken'/832, l='MpServer', x=707.69, y=86.00, z=47.19], EntityCow['Cow'/833, l='MpServer', x=712.31, y=86.00, z=37.78], EntityCow['Cow'/838, l='MpServer', x=712.38, y=86.00, z=39.53], EntityCow['Cow'/839, l='MpServer', x=707.25, y=86.00, z=35.44], EntityCow['Cow'/836, l='MpServer', x=713.53, y=86.00, z=39.53], EntityChicken['Chicken'/837, l='MpServer', x=706.94, y=86.00, z=47.94], EntityCow['Cow'/842, l='MpServer', x=711.13, y=86.00, z=39.53], EntityPig['Pig'/843, l='MpServer', x=711.09, y=86.00, z=45.50], EntityPig['Pig'/840, l='MpServer', x=707.19, y=86.00, z=41.44], EntityPig['Pig'/841, l='MpServer', x=710.94, y=86.00, z=43.44], EntityPig['Pig'/846, l='MpServer', x=707.78, y=86.00, z=42.66], EntityCow['Cow'/847, l='MpServer', x=711.00, y=86.00, z=37.81], EntityCow['Cow'/844, l='MpServer', x=713.53, y=86.00, z=35.44], EntityPig['Pig'/845, l='MpServer', x=713.53, y=86.00, z=41.44], EntityZombie['Zombie'/1222, l='MpServer', x=621.50, y=25.00, z=111.50], EntityCreeper['Creeper'/1217, l='MpServer', x=623.50, y=25.00, z=114.50], EntitySkeleton['Skeleton'/952, l='MpServer', x=770.50, y=40.00, z=147.50], EntitySkeleton['Skeleton'/954, l='MpServer', x=770.50, y=40.00, z=149.50], EntityCreeper['Creeper'/1218, l='MpServer', x=623.50, y=25.00, z=109.50], EntitySkeleton['Skeleton'/951, l='MpServer', x=768.50, y=40.00, z=150.50], EntityCreeper['Creeper'/927, l='MpServer', x=763.97, y=39.00, z=145.47], EntityRabbit['Rabbit'/923, l='MpServer', x=641.22, y=73.00, z=138.59], EntitySlime['Slime'/1256, l='MpServer', x=693.53, y=16.14, z=81.74], EntityItemFrame['entity.ItemFrame.name'/747, l='MpServer', x=711.50, y=55.50, z=67.03], EntityArmorStand['Armor Stand'/746, l='MpServer', x=709.50, y=54.00, z=67.50], EntityItem['item.item.egg'/1974, l='MpServer', x=710.75, y=86.00, z=49.91], EntityArmorStand['Armor Stand'/745, l='MpServer', x=712.50, y=54.00, z=67.25], EntityItemFrame['entity.ItemFrame.name'/744, l='MpServer', x=709.50, y=56.50, z=67.03], EntityItemFrame['entity.ItemFrame.name'/751, l='MpServer', x=710.50, y=56.50, z=67.03], EntityItemFrame['entity.ItemFrame.name'/750, l='MpServer', x=711.50, y=56.50, z=67.03], EntityItemFrame['entity.ItemFrame.name'/749, l='MpServer', x=710.50, y=55.50, z=67.03], EntityItemFrame['entity.ItemFrame.name'/748, l='MpServer', x=712.50, y=56.50, z=67.03], EntityChicken['Chicken'/762, l='MpServer', x=713.06, y=86.00, z=48.81], EntityRabbit['Rabbit'/763, l='MpServer', x=708.94, y=86.00, z=59.28], EntitySheep['Sheep'/760, l='MpServer', x=711.16, y=86.00, z=53.44], EntityItem['item.item.egg'/761, l='MpServer', x=711.00, y=86.00, z=48.38], EntityBat['Bat'/1172, l='MpServer', x=627.75, y=28.10, z=139.53], EntityChicken['Chicken'/766, l='MpServer', x=706.94, y=86.02, z=51.09], EntitySheep['Sheep'/767, l='MpServer', x=708.69, y=86.00, z=53.44], EntityBat['Bat'/1174, l='MpServer', x=621.33, y=26.50, z=137.68], EntitySheep['Sheep'/764, l='MpServer', x=709.97, y=86.00, z=54.28], EntityBat['Bat'/1175, l='MpServer', x=636.45, y=26.05, z=144.38], EntitySheep['Sheep'/765, l='MpServer', x=712.25, y=86.00, z=56.56], EntityChicken['Chicken'/754, l='MpServer', x=708.63, y=86.00, z=48.19], EntityItem['item.item.egg'/755, l='MpServer', x=707.22, y=86.00, z=51.88], EntityBat['Bat'/1178, l='MpServer', x=629.27, y=28.08, z=111.44], EntityChicken['Chicken'/752, l='MpServer', x=713.06, y=86.00, z=48.09], EntityChicken['Chicken'/753, l='MpServer', x=708.72, y=86.00, z=51.78], EntityChicken['Chicken'/758, l='MpServer', x=713.78, y=86.00, z=48.16], EntityChicken['Chicken'/759, l='MpServer', x=706.94, y=86.00, z=51.78], EntityChicken['Chicken'/756, l='MpServer', x=710.94, y=86.00, z=50.16], EntityZombie['Zombie'/1673, l='MpServer', x=771.50, y=53.00, z=79.50], EntityBat['Bat'/1944, l='MpServer', x=660.73, y=17.52, z=5.38], EntityZombie['Zombie'/1675, l='MpServer', x=624.50, y=36.00, z=121.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2489)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 147141104 bytes (140 MB) / 580911104 bytes (554 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.14.1282 Minecraft Forge 11.14.0.1282 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{8.0.14.1282} [Forge Mod Loader] (forge-1.8-11.14.0.1282-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{11.14.0.1282} [Minecraft Forge] (forge-1.8-11.14.0.1282-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.5.82} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.82-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by acters124** [comment]
it looks to be that the redstone ore block emits a "redstone light" but not a power signal.

**Comment by DracroniC** [comment]
I get the exact same error and it only happens when NEI on.  The second a redstone ore block plays it's animation game crash.

**Comment by HeroCC** [comment]
Same here, when I look at Redstone Ore with Highlight tooltips on, it crashes. Turning it off seems to fix it for me. CCC: 1.0.5.34, NEI: 1.0.5.84

**Comment by joosera** [comment]
Happened to me today too, looking at a lit redstone ore block with hilight tooltips on crashes the game.

**Comment by joosera** [comment]
I did some digging, it seems that redstone ore has the id "tile.oreRedstone", but for for some reason lit ore becomes "item.redstone".
![redstone_ore](https://cloud.githubusercontent.com/assets/722048/5825061/5c91c2cc-a0f1-11e4-845a-5e3937a41f11.png)
(I edited *DefaultHighlightHandler.java* to skip the stuff the prints out the redstone power level and instead displays *getUnlocalizedName()* for the item in question)

**Comment by Chicken-Bones** [comment]
Fixed as of 8e56b2e912e9687b9bcb078b0f3961b5f8d436a3 (1.8-1.0.5.86)

**Comment by joosera** [comment]
That still doesn't fix the problem hat lit redstone ore still is called Redstone, but atleast it fixes the crashing. I guess that might be a problem with Minecraft itself, though the WAILA mod seems to very similar code yet produces the correct output, mystifying.

**Comment by Chicken-Bones** [comment]
That's an MC issue that changed with 1.8. You'll notice that using pick
block (NEI's first port of call for identifying the item) doesn't return
anything, so NEI reverts to the dropped item (redstone dust). I don't
intend to hardcode an override for something as small as this, that's the
domain of a mod like WAILA

**Comment by joosera** [comment]
Fair enough.

**Comment by jgwath** [comment]
i get the error when i try to mine the redstone ore not when i use the nei/waila to look at the ore. My crash log looks the same 
"...
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=minecraft:lit_redstone_ore, properties=[]}
..."
As soon as I can figure out how the pastebin works, I can post the full message if you would like.

**Comment by HeroCC** [comment]
@jgwath try updating NEI to the latest dev version, this was fixed a while ago

**Comment by BleeBlaBle** [comment]
This isn't fixed. .104 still crashes with highlight tooltips on while viewing lit redstone ore

**Comment by IronMaiden1993** [comment]
Hello My Friend . i have the same problem and i found the solucion : the old ccc and the new nei . 

NotEnoughItems	1.0.5.104 and CodeChickenCore	1.0.5.34 is the solucion . for me works . excuse me for my inglish i am from argentina xD

**Comment by timvandenhof** [comment]
Stil reproducable with the latest NEI version on Minecraft 1.8.0. Same error as above:
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=minecraft:lit_redstone_ore, properties=[]}

Mod list:
NotEnoughItems-1.8-1.0.5.82-universal
CodeChickenCore-1.8-1.0.5.34-universal
CodeChickenLib-1.8-1.1.2.115-universal
FML 8.99.124.1450
OptiFine_1.8.0_HD_U_D5

**Comment by BirkhoffLee** [comment]
Same here, latest NEI on Minecraft 1.8.0.
